spring:
  profiles:
    include:
      - web
      - mybatis
    active: dev
mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
---
spring:
  profiles: dev
---
spring:
  profiles: test
